package maderski.bluetoothautoplaymusic.maps

enum class MapsLaunchState {
    MAPS_IS_ALREADY_RUNNING,
    REGULAR_MAPS_LAUNCH,
    DRIVING_MODE_MAPS_LAUNCH,
    USE_TIMES_MAPS_LAUNCH,
    DRIVING_MODE_AND_USE_TIMES_MAPS_LAUNCH,
    DIRECTIONS_AND_TIMES_MAPS_LAUNCH,
    EVERYTHING_ENABLED_MAPS_LAUNCH
}